name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Logs.js'
      - 'automate.js'
      - 'dailyLogs.js'
      - 'hourlyLogs.js'
      - 'index.js'
      - 'stats.js'
jobs:
  changes:
      name: Detect Changes in folder
      runs-on: self-hosted
      outputs:
        names: ${{ steps.filter.outputs.changes }}
      steps:
      - uses: actions/checkout@v2
      - name: Detect Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            Logs:
              - 'Logs.js'
            automate:
              - 'automate.js'
            dailyLogs:
              - 'dailyLogs.js'
            hourlyLogs:
              - 'hourlyLogs.js'
            index:
            -   'index.js'
            stats:
            -   'stats.js'
  build:
    needs: changes
    name: ${{matrix.name}} - ${{ matrix.environment }}
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: echo '${{ secrets.ENV_FILE }}' > .env
    - run: echo '${{ needs.changes.outputs.names }}'
    - name: Checking Logs file
      run: |
        pm2 stop Logs.js 
        pm2 start Logs.js
      if: ${{ needs.changes.outputs.names == '["Logs"]' }}
    - name: Checking automate.js file
      run: |
        pm2 stop automate.js
        pm2 start automate.js
      if: ${{ needs.changes.outputs.names == '["automate"]' }}
    - name: Checking dailyLogs file
      run: |
        pm2 stop dailyLogs.js
        pm2 start dailyLogs.js
      if: ${{ needs.changes.outputs.names == '["dailyLogs"]' }}
    - name: Checking hourlyLogs file
      run: |
        pm2 stop hourlyLogs.js
        pm2 start hourlyLogs.js
      if: ${{ needs.changes.outputs.names == '["hourlyLogs"]' }}
    - name: Checking index file
      run: |
        pm2 stop index.js
        pm2 start index.js
      if: ${{ needs.changes.outputs.names == '["index"]' }}
    - name: Checking stats file
      run: |
        pm2 stop stats.js
        pm2 start stats.js
      if: ${{ needs.changes.outputs.names == '["stats"]' }}
    - name: Checking Logs1 file
      run: |
        pm2 stop Logs1.js 
        pm2 start Logs1.js
      if: ${{ needs.changes.outputs.names == '["Logs1"]' }}
